# Generated by Django 4.0.5 on 2022-06-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_remove_resultmodel_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='percent',
            field=models.FloatField(max_length=10),
        ),
    ]
