# Generated by Django 4.0.5 on 2022-07-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_delete_resultmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=500, null=True)),
                ('score', models.IntegerField(max_length=200, null=True)),
            ],
        ),
    ]
